### ISSUE TITLE
Increase minimum PHP version to 7.4

### ISSUE THREAD

**Issue by ocean90** [wearerequired/coding-standards#104]
Previously: #23

Currently we're using 7.1 which is [EOL](https://www.php.net/supported-versions.php). The same is true for 7.2 and active support for 7.3 ends in 4 days.
Therefore, and also as a preparation for 8.0, I'd like us to increase the minimum [PHP version to 7.4](https://www.php.net/manual/de/migration74.new-features.php).

This change should probably be go in with #35 and #58 and other type related rules.

Related: The Slevomat Coding Standard will also drop support for 7.1 soon, see https://github.com/slevomat/coding-standard/issues/1082.

Thoughts? Feedback? Questions?

**Comment by grappler** [comment]
Sounds good. I think most of our projects have been tested and updated to 7.4. We can always override the version for specific versions if need be.

**Comment by ocean90** [comment]
> We can always override the version for specific versions if need be.

Unfortunately that's still not possible because PHPCS 4.0 is not yet released, see https://github.com/wearerequired/coding-standards/issues/23#issuecomment-595674163.
