### ISSUE TITLE
Increase minimum PHP version to 7.0

### ISSUE THREAD

**Issue by grappler** [wearerequired/coding-standards#23]
Currently we have `<config name="testVersion" value="5.6-"/>`. I would like to increase the default to `7.0`. I would prefer to set it down `5.6` as the exception.

If all are agreed I can create a PR.

**Comment by ocean90** [comment]
@grappler Feel free to bump it to 7.0. Projects which still require 5.6 probably don't even use this ruleset.

**Comment by ocean90** [comment]
In https://github.com/wearerequired/coding-standards/commit/7d0dbb9f14ab8ff16f02f26b21804032863e4a7f I actually went ahead and bumped it to 7.1 since that's the version most of our projects are using. By end of the year we should bump it to 7.2, see http://php.net/supported-versions.php.

**Comment by ocean90** [comment]
The upstream issue was closed a few days ago. With [4.0.0](https://github.com/squizlabs/PHP_CodeSniffer/milestone/11) a project config should be able to override the default config.
