### ISSUE TITLE
PHP 8.2

### ISSUE THREAD

**Issue by krokodok** [wearerequired/coding-standards#241]
To make the package [PHPCompatibility/PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility), which is a dependency of [PHPCompatibility/PHPCompatibilityWP](https://github.com/PHPCompatibility/PHPCompatibilityWP), work with PHP 8.2, the developers suggest using the `develop`-Branch as version `9.9.99` until there is a new release: 
- https://github.com/PHPCompatibility/PHPCompatibility/issues/1468
- https://github.com/PHPCompatibility/PHPCompatibility/issues/1653

**Comment by ocean90** [comment]
Do you have an example code snippet/project where this was an issue?

**Comment by krokodok** [comment]
I encountered these problems at https://github.com/wearerequired/autofit-garages/, but I don't remember exactly how to reproduce it. Maybe this can somehow work otherwise. I did in fact not encounter the same problem at other PHP 8.2 websites, but maybe the project setups are too different.

**Comment by krokodok** [comment]
I just encountered the problem in [https://](https://github.com/wearerequired/trailworks-theme) as well. The problem occurs *only* in VS Code and that was the reason for my update.

### Recreate
- I am currently using the extension [PHP Sniffer](https://marketplace.visualstudio.com/items?itemName=wongjn.php-sniffer) (others stopped working for me)

- Set `wearerequired/coding-standards` to `^3.0`
- Set local development PHP version to 8.2
- PHPCS in VS Code will throw errors when running `phpcs` on save by extension

- Set `wearerequired/coding-standards` to `^5.0`
- PHPCS in VS Code will still throw errors when running `phpcs` on save by extension

- Set `wearerequired/coding-standards` to `dev-master` **AND** `phpcompatibility/php-compatibility` to `"dev-develop as 9.9.99"`
- Checking will work again

![grafik](https://github.com/wearerequired/coding-standards/assets/10128264/9bf3b8eb-bd76-475f-9844-92afb46d8b96)

```
An error occurred during processing; checking has been aborted. The error message was: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/jeffchi/Projects/trailworks/wordpress/content/themes/trailworks-theme/vendor/phpcompatibility/php-compatibility/PHPCompatibility/Sniff.php on line 131\nThe error originated in the .PHPCompatibility. sniff on line 131.
```

If this is just an individual error for my IDE setup, that is okay. It still works from CLI.

**Comment by ocean90** [comment]
Interesting! I'll give the extension a try. I'm using [shevaua.phpcs](https://marketplace.visualstudio.com/items?itemName=shevaua.phpcs) and [persoderlind.vscode-phpcbf](https://marketplace.visualstudio.com/items?itemName=persoderlind.vscode-phpcbf).

**Comment by ocean90** [comment]
@krokodok I was able to reproduce this (also with my extensions) and it's actually a PHPCS config error. The [upgrade guide for 5.0.0 ](https://github.com/wearerequired/coding-standards/releases/tag/5.0.0) includes the note that you have to set `minimum_supported_wp_version` and `testVersion` in `phpcs.xml.dist`. Once you add the necessary config the error is gone and you get the sniff to use the correct version for any compatibility checks.

[Line 131 of Sniff.php is about the `testVersion`](https://github.com/PHPCompatibility/PHPCompatibility/blob/9fb324479acf6f39452e0655d2429cc0d3914243/PHPCompatibility/Sniff.php#L131). In the develop branch [a string cast operator is used](https://github.com/PHPCompatibility/PHPCompatibility/blob/8f663b693e14f98c222d197c3ecead427bf6f663/PHPCompatibility/Helpers/ScannedCode.php#L103C13-L103C17).

**Comment by krokodok** [comment]
@ocean90 Super, thanks for taking the time to check!

**Comment by krokodok** [comment]
@ocean90 Could recreate it again regarding the sniff `WordPress.NamingConventions.PrefixAllGlobals`, even when the data from the migration guide is set.

This led me again to the same issue in the PHPCompatibility-repo which explained to use `dev`-branch: https://github.com/WordPress/WordPress-Coding-Standards/issues/2035

**Comment by krokodok** [comment]
Encountered a similar error again with the sniff `WordPress.NamingConventions.PrefixAllGlobals`. This led me to the original issue in the PHPCompatibility repo that told to use the `dev` branch in the first place: https://github.com/WordPress/WordPress-Coding-Standards/issues/2203
