### ISSUE TITLE
Performance: Add a rule to root-namespace special compiled PHP functions

### ISSUE THREAD

**Issue by ocean90** [wearerequired/coding-standards#60]
See `zend_try_compile_special_func()` in [https://github.com/php/php-src/blob/PHP-7.4/Zend/zend_compile.c](https://github.com/php/php-src/blob/6e88f19346236aad75779c9d91fffe4987786894/Zend/zend_compile.c#L3746) for the list of special functions. The functions will be replaced by opcodes at compile time, but only if it's clear that the global native functions will be used.

Related: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.16.1/src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php

**Comment by ocean90** [comment]
This will be possible with 6.2.0 of Slevomat Coding Standard.
https://github.com/slevomat/coding-standard/issues/949#issuecomment-604917030

**Comment by grappler** [comment]
Do you have an example with PHP code?

**Comment by ocean90** [comment]
You can find the list of special functions [here](https://github.com/slevomat/coding-standard/blob/6.2.0/SlevomatCodingStandard/Helpers/FunctionHelper.php#L39-L73). The understand the difference compare https://3v4l.org/qbomn/vld#output with https://3v4l.org/b873e/vld#output.
