### ISSUE TITLE
Disallow @throws tags or add them to group annotations

### ISSUE THREAD

**Issue by ocean90** [wearerequired/coding-standards#66]
The WordPress coding standard for docs includes the `Squiz.Commenting.FunctionCommentThrowTag` rule by default. This ensures that a `@throws` tag is added to the DocBlock otherwise you get `Missing @throws tag in function comment
(Squiz.Commenting.FunctionCommentThrowTag.Missing)`.

Once added this currently triggers another error: `Incorrect order of annotations groups.
(SlevomatCodingStandard.Commenting.DocCommentSpacing.IncorrectOrderOfAnnotationsGroup)`. This is due to https://github.com/wearerequired/coding-standards/pull/62.

@wearerequired/developers  Should @throws tags be added to the DocBlock? If yes, in which group should they be added?

**Comment by grappler** [comment]
We have not used many exceptions in our code so the need for it is low but by not supporting it means there will be a CS notice the few times we have used it or if we plan to use it more in the future.

I suppose I would put the `@throws` between the parameters and return.
```
/**
 * Sends notification for an extended job listing.
 *
 * @internal Foo.
 *
 * @since 1.0.0
 * @deprecated 2.0.0
 *
 * @link https://google.de
 * @see get_the_title()
 * @uses get_permalink()
 *
 * @param int $job_id Post ID of the job listing.
 * @throws InvalidArgumentException if the provided argument is not of type array.
 * @return bool True on success, false on failure.
 */
```

**Comment by ocean90** [comment]
I don't think we should "hide" them between the parameter and the return value. For me it would be easier to scan them when they are above the parameters or after return.

```php
/**
 * Something.
 *
 * @link https://google.de
 *
 * @param int $something Something
 * @return bool True on success, false on failure.
 * @throws InvalidArgumentException If the provided argument is not of type array.
 * @throws AnotherException If something is not right.
 */
```

```php
/**
 * Something.
 *
 * @link https://google.de
 * 
 * @throws InvalidArgumentException If the provided argument is not of type array.
 * @throws AnotherException If something is not right.
 *
 * @param int $something Something
 * @return bool True on success, false on failure.
 */
```

My favorite is the second example.

**Comment by grappler** [comment]
I am Ok with the second example too.
